Implementation reset password function
BinaryStudioAcademy/bsa-winter-2022-look pull request #13
Opened 2022-02-09 16:40 UTC by RuslanKamenev

2022-02-09 17:26 UTC, RomanMahola requested changes

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Actions/Auth/PasswordChangeAction.php
> +        if (!PasswordResets::where('token', $request->get('token'))) {
Provide into repository

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Actions/Auth/PasswordChangeAction.php
> +        if($resetData->get()->first()->toArray()['email'] !== $request->get('email')) {
Identation

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Actions/Auth/PasswordChangeAction.php
> +        if(User::where('email', $request->get('email'))->update(array('password' => $request->get('password')))) {
array [
  'password' => ''code"
]

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Console/Kernel.php
> +        $schedule->command('auth:clear-resets')->hourly();
valdiate 19:59

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Http/Controllers/Api/Auth/ForgotPasswordController.php
> +        return response()->json([], 204);
use consts

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Http/Requests/Api/Auth/ForgotPasswordRequest.php
> +
declare

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Http/Requests/Api/Auth/PasswordChangeRequest.php
> +            "password" => 'required',
confirmed

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Http/Requests/Api/Auth/PasswordChangeRequest.php
> +            "token" => 'required'
string

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Mail/ForgotPasswordEmail.php
> +    /**
delete comments

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Mail/ForgotPasswordEmail.php
> +    public function __construct(public array $token)
empty constructor

2022-02-09 17:26 UTC, RomanMahola commented on backend/app/Mail/ForgotPasswordEmail.php
> +     * Build the message.
comments

2022-02-09 17:26 UTC, RomanMahola commented on backend/database/factories/RoleFactory.php
> +    /**
comments

2022-02-09 17:26 UTC, RomanMahola commented on backend/resources/views/email/forgot_password.blade.php
> +    <a href="{{ route('password.reset-view', $token['value']) }}">Reset password link</a>
Check

2022-02-09 23:17 UTC, RuslanKamenev commented
Remove comments, add const and declaration type.

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/app/Http/Controllers/Api/Auth/ForgotPasswordController.php
> +    const RESPONSE_STATUS_NO_CONTENT = 204;
Remove const

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/app/Mail/ForgotPasswordEmail.php
> +    public function __construct(public string $token)
Change string to private

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/app/Repositories/PasswordReset/PasswordResetRepository.php
> +        return PasswordResets::firstWhere('token', $token);
Change to findOrFail()

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/database/factories/RoleFactory.php
> +
Change to seed

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/database/seeders/DatabaseSeeder.php
> +        /**
Remove 17-25

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/resources/views/auth/reset_password.blade.php
> +<!DOCTYPE html>
Remove file

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/resources/views/errors/404.blade.php
> +<h2>{{ $exception->getMessage() }}</h2>
Remove file

2022-02-15 16:58 UTC, RuslanKamenev commented on backend/resources/views/forgot.blade.php
> +<!DOCTYPE html>
Remove file

2022-02-16 12:47 UTC, RomanMahola approved these changes

2022-02-16 12:58 UTC, merged